### ISSUE TITLE
为什么要增加一个pdf转svg的过程，直接使用pdf.js实现网上浏览是否更好？

### ISSUE THREAD

**Issue by xdsnet** [TruthHun/DocHub#1]
现在通过pdf.js在线浏览pdf的性能应该比较好了，为什么还要增加pdf转svg过程去浏览svg？
主要通过pdf.js浏览甚至可以保留pdf的链接特性，更是方便啊。

**Comment by TruthHun** [comment]
最初的方案是使用`pdf.js`提供阅读的，pdf.js需要把整个PDF文档下载下来才能展示内容，而且，如果你的PDF文档是要收费才能提供下载的话，pdf.js会暴露文件直链，积分下载根本就没有意义了。而且，目前成熟的文库站点，都没有使用pdf.js作为阅读展现，肯定也有出于这方面的考虑。
[https://github.com/TruthHun/DocHub#read-pdf](https://github.com/TruthHun/DocHub#read-pdf)

**Comment by robbenmu** [comment]
百度文库是我做的，我来回答下为什么没用pdf.js，因为在我开发的时候还没有pdf.js。。。 我离职了，那边只是维护状态

**Comment by TruthHun** [comment]
@ydfzgyj 上面已经说明不用`pdf.js`的原因了

**Comment by shuyabin** [comment]
这个如果设置成收费的话.咱们可以观看的是免费的前10页生成一个pdf 付费后链接改变成完整的链接。
