### ISSUE TITLE
 error '_xsrf' argument missing from POST when install

### ISSUE THREAD

**Issue by luodanwg** [TruthHun/DocHub#18]
用的release4 DocHub v2.0的最新版本
![image](https://user-images.githubusercontent.com/22299020/44188492-6fcd9600-a150-11e8-95fb-0397790bce88.png)
install界面，输入完数据库信息提交后提示错误，请问怎么解决？
 error '_xsrf' argument missing from POST

**Comment by bay1** [comment]
在install.html文件中68行加下
```
{{.xsrfdata}}
```
就可以了

**Comment by luodanwg** [comment]
by last version ,solved.
