### ISSUE TITLE
处理失败：exec: "soffice": executable file not found in $PATH

### ISSUE THREAD

**Issue by mrsongindezhou** [TruthHun/DocHub#32]
你好，我的文档为啥打不开预览效果呢
日志提示：处理失败：exec: "soffice": executable file not found in $PATH
我用的centos7，pdf2svg没有找到安装包，跟这个有关系吗

**Comment by TruthHun** [comment]
`pdf2svg`自己网上找源码进行编译，但是必须是最新版本.

`soffice`是因为你没安装libreoffice或者openoffice.

centos下很多依赖没法跑，建议用Ubuntu。
