### ISSUE TITLE
竟然不支持.txt文档在线预览？

### ISSUE THREAD

**Issue by tansuo1989** [TruthHun/DocHub#4]
看到这个提示：当前格式(txt)文档暂时不支持在线预览，请下载原文档对内容进行浏览。

复杂的实现了，最简单的却忘了。

**Comment by TruthHun** [comment]
你好。之前其实是实现了txt在线浏览的，但是后来发现，gbk编码或者其他一些txt在通过`soffice`转成PDF的时候，出现了乱码。txt的，会尽快想办法解决。如果你有什么好的解决办法，也可以提出来。也欢迎你加入我们的QQ交流群，`QQ交流群：457803862(猿军团)`

**Comment by tansuo1989** [comment]
噢，原来是转pdf的时候有问题，我没有转过。
但，先把gbk转成utf-8，再转pdf也会有乱码的问题吗？

**Comment by dancelion** [comment]
我之前项目用的`Unoconv`转换的pdf，目前没发现乱码的问题

**Comment by hueidou** [comment]
不清楚这个问题是否解决。如果没有，考虑[Mozilla Universal Charset Detector](https://www-archive.mozilla.org/projects/intl/chardet.html)，应该算是比较标准的方式。

有些语言有专用的库来判断文本编码，大都是根据文本特征进行判断，返回最准确的编码。不过都是有误判。

**Comment by TruthHun** [comment]
目前已支持`txt`在线阅读
